
import type { Metadata } from "next";
import AddressManagement from "@/components/Shippingmenu/AddressManagement";
import Subtotal from "@/components/Shippingmenu/Subtotal";
import { getSession } from "@/app/api/auth/func/getEnrolls";
import { getCart } from "@/lib/db/cartDB";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  try {
    const session = await getSession();
    if (!session || !session.user || !session.user.user_id) {
      throw new Error("User session or user ID not found.");
    }
    
    const allCart = await getCart({ customer_id: session.user.user_id });

    return (
      <div className="h-screen mt-8 p-10 justify-center ml-[70px] mr-[50px]">
        <div className="border-b-2 mb-4 w-6/12 pl-2 ml-[-10px]">
          <p className="text-2xl font-bold inline-block">Shipping address</p>
          <p className="text-sm text-[#AAAAAA] inline-block ml-3">
            Select your address
          </p>
        </div>
        <div className="grid grid-cols-11 grid-row-4 gap-2">
          <div className="row-span-1  col-span-6 flex items-center justify-center">
            <AddressManagement />
          </div>
          <div className="row-span-4 col-span-5 border-l-2 border-[#000000]">
            <Subtotal data={allCart}/>
          </div>
          <div className="row-span-3 col-span-6">
            <main className="grow">{children}</main>
          </div>
        </div>
      </div>
    );
  } catch (error) {
    console.error("Error fetching cart:", error);
    // You may want to render an error component or redirect to handle this error
    return <div>Error fetching cart data.</div>;
  }
};

