import SideNavbar from "@/components/SideNavBar";
import TopBar from "@/components/TopBar";
import type { Metadata } from "next";
import { getSession } from "@/app/api/auth/func/getEnrolls";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  const session = await getSession();
  return (
    <div className="flex h-screen overflow-hidden relative">
      <SideNavbar />
      <div className="flex-1 overflow-auto">
        <TopBar user={session.user}/>
        <main className="grow ">{children}</main>
      </div>
    </div>
  );
}
